### ISSUE TITLE
Height of Calendar.

### ISSUE THREAD

**Issue by prasadshirvandkar** [jMavarez/MaterialCalendar#1]
Can't Set any Custom Height for CalendarView..it just stuck with the Default Height in Layout. -_- -_- -_- -_-????????????????? -_- -_- -_- -_-

**Comment by jMavarez** [comment]
No, you can't (Design reasons).

**Comment by prasadshirvandkar** [comment]
No..Worries...I have Changed the Attributes Suitable for App in Library Code..Now it is good..Thanks for the Amazing Library.

**Comment by jMavarez** [comment]
Awesome, I'm happy that you are using it. Thanks!
